os: Visual Studio 2019
platform: x64

environment:
 BOOST_ROOT: C:\Libraries\boost_1_71_0
 BOOST_LIBRARYDIR: C:\Libraries\boost_1_71_0\lib32-msvc-14.0
 RAPIDJSON_URL: https://github.com/Tencent/rapidjson.git
 GETTEXTURL: https://github.com/mlocati/gettext-iconv-windows/releases/download/v0.19.8.1-v1.14/gettext0.19.8.1-iconv1.14-shared-32.zip

version: 1.0.{build}

only_commits:
  message: /build/

before_build:
 - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
 - cmd: mkdir sdk
 - cmd: mkdir build
 - cmd: cd sdk
 - cmd: SET RJPATH=%CD%\rapidjson
 - cmd: git clone %RAPIDJSON_URL%
 - cmd: SET include=%RJPATH%\include;%include%
 - cmd: mkdir ttscmd
 - cmd: set lib=%BOOST_LIBRARYDIR%;%lib%
 - ps: $wc = New-Object System.Net.WebClient
 - ps: $wc.DownloadFile("$env:GETTEXTURL", "$pwd\gettext.zip")
 - ps: Expand-Archive gettext.zip -DestinationPath $pwd\gettext
 - cmd: PATH=%CD%\gettext\bin;%PATH%
 - cmd: cd ..

build_script:
 - cmd: cd build
 - cmd: cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=..\ttscmd -DBUILD_UNICODE=ON -DBUILD_DLL=ON ..
 - cmd: nmake
 - cmd: nmake install
 - cmd: cd ..
 
artifacts:
  - path: ttscmd
    name: ttscmd
    type: zip 
 
deploy:
  release: ttscmd-v$(appveyor_build_version)
  description: 'TTS command line app'
  provider: GitHub
  auth_token:
    secure: Xco8oPvJtHjFpMBk9cRFQ4hK/OC79n0XEuPe1O2va6Aa/v474AbcuIhrmMnPQbbc # your encrypted token from GitHub
      
  draft: true
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: false        # deploy on tag push only

