os: Visual Studio 2015
platform: x86

environment:
 BOOST_LIBRARYDIR: C:\Libraries\boost_1_63_0\lib32-msvc-14.0
 ICU_URL: 
    secure: 4xmu+DdVKnFWK/zs5sdwDb0ewFjeV1cGrubA/KVF5vjTvpWfvNGRKTWNwXCmVN4zHeQePiH5cr2x35hMmTt+3A==
 BOOST_URL: 
    secure: 4xmu+DdVKnFWK/zs5sdwDb0ewFjeV1cGrubA/KVF5vhTz96UWrDXdz21PoyggI3HgH/iF6O95wTTfpqKUbF2Ew==

version: 1.0.{build}

only_commits:
 message: /build/
 
cache:
  - sdk -> .appveyor.yml

build_script:
 - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
 - cmd: SET include=%BOOST_ROOT%\include;%include%
 - cmd: SET lib=%BOOST_LIBRARYDIR%;%lib%
 - cmd: mkdir ttscmd
 - cmd: mkdir build
 - cmd: mkdir sdk
 - cmd: cd sdk
 - ps: $client = new-object System.Net.WebClient
 - ps: $path = "$PWD\icu.zip" 
 - ps: $client.DownloadFile($ICU_URL, "$pwd\icu.zip")
 - ps: $path = "$PWD\boost.zip"
 - ps: $client.DownloadFile($BOOST_URL, "$pwd\boost.zip")
 - ps: Expand-Archive "icu.zip" "."
 - ps: Expand-Archive "boost.zip" "."
 - cmd: SET BOOST_ROOT=%PWD%\boost
 - cmd: SET ICU_ROOT=%PWD%\icu
 - cmd: SET include=%BOOST_ROOT%\include;%ICU_ROOT%\include;%include%
 - cmd: SET lib=%BOOST_ROOT%\lib;%ICU_ROOT%\lib;%lib%
 - cmd: cd ..
 - cmd: cd build
 - cmd: cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=..\ttscmd ..
 - cmd: nmake
 - cmd: nmake install
 
deploy:
  release: ttscmd-v$(appveyor_build_version)
  description: 'TTS command line app'
  provider: GitHub
  auth_token:
    secure: Xco8oPvJtHjFpMBk9cRFQ4hK/OC79n0XEuPe1O2va6Aa/v474AbcuIhrmMnPQbbc # your encrypted token from GitHub
  artifact: /ttscmd/.*            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
