os: Visual Studio 2015
platform: x86

environment:
 BOOST_ROOT: C:\Libraries\boost_1_63_0
 BOOST_LIBRARYDIR: C:\Libraries\boost_1_63_0\lib32-msvc-14.0
 RAPIDJSON_URL: https://github.com/Tencent/rapidjson.git

version: 1.0.{build}

only_commits:
  message: /build/

before_build:
 - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
 - cmd: mkdir sdk
 - cmd: mkdir build
 - cmd: cd sdk
 - cmd: SET RJPATH=%PWD%\rapidjson
 - cmd: git clone %RAPIDJSON_URL%
 - cmd: SET include=%RJPATH%\include;%include%
 - cmd: cd ..
 - cmd: mkdir ttscmd
 - cmd: set lib=%BOOST_LIBRARYDIR%;%lib%

build_script:
 - cmd: cd build
 - cmd: cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=..\ttscmd -DBUILD_UNICODE=ON -DBUILD_DLL=ON ..
 - cmd: nmake
 - cmd: nmake install
 - cmd: cd ..
 
artifacts:
  - path: ttscmd
    name: ttscmd
    type: zip 
 
deploy:
  release: ttscmd-v$(appveyor_build_version)
  description: 'TTS command line app'
  provider: GitHub
  auth_token:
    secure: Xco8oPvJtHjFpMBk9cRFQ4hK/OC79n0XEuPe1O2va6Aa/v474AbcuIhrmMnPQbbc # your encrypted token from GitHub
      
  draft: true
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: false        # deploy on tag push only

