stages:
    - build

win10-build:
    stage: build
    tags:
        - native
        - windows
        - vs2019
    before_script:
        - cmd /c "echo mkdir tts > mybuild.bat"
        - cmd /c "echo cd tts >> mybuild.bat"
        - cmd /c "echo call vs >> mybuild.bat"
        - cmd /c 'echo cmake -G "NMake Makefiles -DCMAKE_BUILD_TYPE=Release .. >> mybuild.bat'
        - cmd /c "echo make >> mybuild.bat"

    script:
        - cmd /c "mybuild.bat"
