#ifndef TTSCMD_TTS_VERSION_H__
#define TTSCMD_TTS_VERSION_H__

#define CLU_s_APPLICATION_NAME "clutts"
#define CLU_s_TTS_GIT_BRANCH "master"
#define CLU_s_TTS_GIT_COMMIT_HASH "f23e6fc"
#define CLU_s_TTS_MAJOR_VERSION 1
#define CLU_s_TTS_MINOR_VERSION 0
#define CLU_s_TTS_GIT_REV_COUNT 28
#define CLU_s_TTS_VERSION "1.0.28"

#endif //TTSCMD_TTS_VERSION_H__
