#ifndef TTS_VERSION_H
#define TTS_VERSION_H

#define TTSCMD_APPLICATION_NAME "ttscmd"
#define TTSCMD_GIT_BRANCH "master"
#define TTSCMD_GIT_COMMIT_HASH "12e3a1a"
#define TTSCMD_MAJOR_VERSION 1
#define TTSCMD_MINOR_VERSION 0
#define TTSCMD_GIT_REV_COUNT 103
#define TTSCMD_VERSION "1.0.103"

#endif //TTS_VERSION_H
