#ifndef TTS_VERSION_H
#define TTS_VERSION_H

#define TTSCMD_APPLICATION_NAME "ttscmd"
#define TTSCMD_GIT_BRANCH "master"
#define TTSCMD_GIT_COMMIT_HASH "49c5c5c"
#define TTSCMD_MAJOR_VERSION 1
#define TTSCMD_MINOR_VERSION 0
#define TTSCMD_GIT_REV_COUNT 104
#define TTSCMD_VERSION "1.0.104"

#endif //TTS_VERSION_H
